FROM python:3.12.7-slim-bullseye

RUN apt update -y &&  \
    apt upgrade -y && \
    apt install make -y && \
    apt clean && \
    pip install jupyterlab matplotlib pandas scikit-learn tensorflow && \
    pip install nltk
